# Generated by Django 5.2.5 on 2025-08-28 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نوع درخواست')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('code', models.CharField(max_length=10, verbose_name='کد خطا')),
                ('content', models.TextField(verbose_name='پیام شما (توضیحات کامل مشکل یا سؤال خود را وارد کنید)')),
                ('request_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.request_type', verbose_name='نوع درخواست')),
            ],
        ),
    ]
